[package]
name = "pipa"
version = "0.0.0"
edition = "2021"
authors = ["Muhammad Fathir Irhas <mfathirirhas@gmail.com>"]
description = "Pipe Operator Library"
license = "MIT"
repository = "https://github.com/mfirhas/pipa"

[dependencies]
